server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:./data/database
    username: sa
    password: sa
